

services:
  # User API service
  user-api:
    build: 
      context: .
      dockerfile: User/dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/taskflow
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=ab34f68038a4c1eb98c8528a7fd36ee46b90ec2a959a1a018f6407d555f83841
    depends_on:
      - postgres
      - redis
    networks:
      - taskflow-network
    # task-api service
  task-api:
    build: 
      context: .
      dockerfile: Task/dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/taskflow
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=ab34f68038a4c1eb98c8528a7fd36ee46b90ec2a959a1a018f6407d555f83841
    depends_on:
      - postgres
      - redis
    networks:
      - taskflow-network

  # Celery worker
  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/taskflow
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    networks:
      - taskflow-network

  # Celery beat for scheduled tasks
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app beat --loglevel=info --schedule=/tmp/celerybeat-schedule
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/taskflow
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    networks:
      - taskflow-network

  # PostgreSQL database
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskflow
    ports:
      - "5432:5432"
    networks:
      - taskflow-network

  # Redis for Celery broker and cache
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - taskflow-network

  # Flower for monitoring Celery tasks
  flower:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - taskflow-network

volumes:
  postgres_data:
  redis_data:

networks:
  taskflow-network:
    driver: bridge